name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'doc/**'
      - 'examples/**'
      - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: cmake preparation
      run: mkdir build && cd build && cmake ..

    - name: build
      working-directory: ./build
      run: make VERBOSE=1

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fiscodegen-linux-x64
        path: /home/runner/work/fiscodegen/fiscodegen/build/build/bin/fiscodegen
