name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'doc/**'
      - 'examples/**'
      - '.vscode/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: 3.21.3

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Upload artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: build