name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'doc/**'
      - 'examples/**'
      - '.vscode/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: 3.21.3

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Upload release
      if: matrix.os == 'ubuntu-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: fiscodegen-latest-linux
        path: build/build

   - name: Upload release
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: fiscodegen-latest-windows
        path: build/build
